image: Visual Studio 2017

version: '1.0.{build}'

branches:
  only:
  - master

platform:
  - ARM

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - ps: msbuild /t:restore raspberry\windows-iot\MetecDriver\MetecDriver.sln
  
build:
  project: raspberry\windows-iot\MetecDriver\MetecDriver.sln
  parallel: false
  verbosity: normal